server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/tlonline?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
      # data-location: classpath:sql/config-data.sql
      # schema-location: classpath:sql/config-schema.sql
  jpa:
    hibernate:
      # update代表entity更新时会更新数据库表，none表示交给开发者处理表创建等工作，hibernate不处理
      ddl-auto: update 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
