server:
  port: 8084

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:mysql://localhost:3306/tlonline?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: embedded
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect